var Cards = [];
var CName = [];

function SetCardData(){
	Cards.push({id:"A000",type:"C",color:"CN",name:"Evo Card",cost:"0",plus:"",st:"40",hp:"40",img:"puppydragon",rare:"E",keyword:""});
	Cards.push({id:"A001",type:"C",color:"CN",name:"Archchemic",cost:"40",plus:"",st:"20",hp:"30",img:"archchemic",rare:"R",keyword:"neutralizes:scroll"});
	Cards.push({id:"A002",type:"C",color:"CN",name:"Archbishop",cost:"50",plus:"",st:"30",hp:"30",img:"archbishop",rare:"N",keyword:"unyielding:creature:spell"});
	Cards.push({id:"A003",type:"C",color:"CN",name:"Armored Dragon",cost:"100",plus:"",st:"50",hp:"60",img:"armoreddragon",rare:"R",keyword:"attacks:first:creature:spell:damage"});
	Cards.push({id:"A004",type:"C",color:"CN",name:"Ironmonger",cost:"10",plus:"",st:"20",hp:"30",img:"ironmonger",rare:"S",keyword:"creature:spell:draw"});
	Cards.push({id:"A005",type:"C",color:"CN",name:"Ogre Lord",cost:"70",plus:"",st:"40",hp:"50",img:"ogrelord",rare:"S",keyword:""});
	Cards.push({id:"A006",type:"C",color:"CN",name:"Ground Gear",cost:"60",plus:"",st:"20",hp:"40",img:"groundgear",rare:"R",keyword:"support:neutralizes:scroll"});
	Cards.push({id:"A007",type:"C",color:"CN",name:"Creeping Coin",cost:"20",plus:"",st:"10",hp:"30",img:"creepingcoin",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"A008",type:"C",color:"CN",name:"Great Fossil",cost:"30",plus:"D",st:"0",hp:"30",img:"greatfossil",rare:"S",keyword:"defensive"});
	Cards.push({id:"A009",type:"C",color:"CN",name:"Clockwork Owl",cost:"10",plus:"",st:"20",hp:"20",img:"clockworkowl",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"A010",type:"C",color:"CN",name:"Golden Totem",cost:"0",plus:"",st:"0",hp:"30",img:"goldentotem",rare:"S",keyword:"defensive:creature:spell:gain:magic"});
	Cards.push({id:"A011",type:"C",color:"CN",name:"Goblin",cost:"0",plus:"",st:"20",hp:"30",img:"goblin",rare:"N",keyword:""});
	Cards.push({id:"A012",type:"C",color:"CN",name:"Samurai",cost:"50",plus:"",st:"50",hp:"30",img:"samurai",rare:"S",keyword:"instant:death"});
	Cards.push({id:"A013",type:"C",color:"CN",name:"Thief",cost:"30",plus:"",st:"20",hp:"40",img:"thief",rare:"N",keyword:"item:destruction"});
	Cards.push({id:"A014",type:"C",color:"CN",name:"Shapeshifter",cost:"30",plus:"",st:"20",hp:"20",img:"shapeshifter",rare:"R",keyword:"creature:spell"});
	Cards.push({id:"A015",type:"C",color:"CN",name:"Shadowgeist",cost:"60",plus:"",st:"40",hp:"30",img:"shadowgeist",rare:"R",keyword:"attacks:first:unyielding"});
	Cards.push({id:"A016",type:"C",color:"CN",name:"Sky Gear",cost:"40",plus:"",st:"40",hp:"20",img:"skygear",rare:"R",keyword:"support:attacks:first"});
	Cards.push({id:"A017",type:"C",color:"CN",name:"Skeleton",cost:"30",plus:"",st:"30",hp:"40",img:"skeleton",rare:"N",keyword:"regenerates"});
	Cards.push({id:"A018",type:"C",color:"CN",name:"Statue",cost:"10",plus:"",st:"0",hp:"50",img:"statue",rare:"N",keyword:"defensive"});
	Cards.push({id:"A019",type:"C",color:"CN",name:"Steam Gear",cost:"60",plus:"",st:"50",hp:"50",img:"steamgear",rare:"S",keyword:""});
	Cards.push({id:"A020",type:"C",color:"CN",name:"Stone Jizo",cost:"50",plus:"",st:"10",hp:"30",img:"stonejizo",rare:"R",keyword:"defensive:untargetable:terrain:change"});
	Cards.push({id:"A021",type:"C",color:"CN",name:"Saint",cost:"50",plus:"",st:"30",hp:"30",img:"saint",rare:"S",keyword:"instant:death:neutralizes"});
	Cards.push({id:"A022",type:"C",color:"CN",name:"Tyrannosaurus",cost:"75",plus:"",st:"50",hp:"60",img:"tyrannosaurus",rare:"S",keyword:""});
	Cards.push({id:"A023",type:"C",color:"CN",name:"Decoy",cost:"50",plus:"D",st:"0",hp:"10",img:"decoy",rare:"R",keyword:"neutralizes:reflects"});
	Cards.push({id:"A024",type:"C",color:"CN",name:"Trojan Horse",cost:"30",plus:"",st:"0",hp:"30",img:"trojanhorse",rare:"N",keyword:"support:penetrates"});
	Cards.push({id:"A025",type:"C",color:"CN",name:"Nil-Vana",cost:"70",plus:"D",st:"40",hp:"40",img:"nilvana",rare:"R",keyword:"support:attacks:first:creature:spell:damage"});
	Cards.push({id:"A026",type:"C",color:"CN",name:"Ninja",cost:"70",plus:"",st:"40",hp:"40",img:"ninja",rare:"R",keyword:"attacks:first:scroll:critical"});
	Cards.push({id:"A027",type:"C",color:"CN",name:"Halfling",cost:"50",plus:"",st:"30",hp:"30",img:"halfling",rare:"N",keyword:"untargetable"});
	Cards.push({id:"A028",type:"C",color:"CN",name:"Hidebehind",cost:"40",plus:"",st:"30",hp:"40",img:"hidebehind",rare:"S",keyword:"creature:spell:enchant"});
	Cards.push({id:"A029",type:"C",color:"CN",name:"Baldanders",cost:"20",plus:"",st:"0",hp:"30",img:"baldanders",rare:"N",keyword:""});
	Cards.push({id:"A030",type:"C",color:"CN",name:"Bandit",cost:"20",plus:"",st:"20",hp:"20",img:"bandit",rare:"N",keyword:"support:gain:magic"});
	Cards.push({id:"A031",type:"C",color:"CN",name:"Beast Gear",cost:"40",plus:"",st:"30",hp:"30",img:"beastgear",rare:"S",keyword:"neutralizes:scroll:untargetable"});
	Cards.push({id:"A032",type:"C",color:"CN",name:"Fighter",cost:"30",plus:"",st:"40",hp:"40",img:"fighter",rare:"N",keyword:""});
	Cards.push({id:"A033",type:"C",color:"CN",name:"Borgess",cost:"40",plus:"",st:"30",hp:"30",img:"borgess",rare:"R",keyword:"boost"});
	Cards.push({id:"A034",type:"C",color:"CN",name:"Migoal",cost:"40",plus:"D",st:"40",hp:"40",img:"migoal",rare:"S",keyword:"critical:neutralizes"});
	Cards.push({id:"A035",type:"C",color:"CN",name:"Living Armor",cost:"70",plus:"",st:"0",hp:"40",img:"livingarmor",rare:"S",keyword:""});
	Cards.push({id:"A036",type:"C",color:"CN",name:"Living Amulet",cost:"60",plus:"",st:"20",hp:"10",img:"livingamulet",rare:"S",keyword:""});
	Cards.push({id:"A037",type:"C",color:"CN",name:"Living Glove",cost:"70",plus:"",st:"0",hp:"30",img:"livingglove",rare:"R",keyword:""});
	Cards.push({id:"A038",type:"C",color:"CN",name:"Living Helmet",cost:"50",plus:"",st:"20",hp:"30",img:"livinghelmet",rare:"S",keyword:""});
	Cards.push({id:"A039",type:"C",color:"CN",name:"Living Bomb",cost:"60",plus:"",st:"10",hp:"30",img:"livingbomb",rare:"R",keyword:""});
	Cards.push({id:"A040",type:"C",color:"CN",name:"Lunatic Hare",cost:"30",plus:"",st:"20",hp:"30",img:"lunatichare",rare:"S",keyword:""});
	Cards.push({id:"A041",type:"C",color:"CN",name:"Legendary Pharos",cost:"50",plus:"D",st:"40",hp:"50",img:"legendarypharos",rare:"R",keyword:"defensive"});
	Cards.push({id:"A042",type:"C",color:"CN",name:"Red Cap",cost:"30",plus:"D",st:"30",hp:"30",img:"redcap",rare:"S",keyword:"boost"});
	Cards.push({id:"A043",type:"C",color:"CN",name:"Rock Titan",cost:"90",plus:"",st:"70",hp:"70",img:"rocktitan",rare:"R",keyword:""});
	Cards.push({id:"A044",type:"C",color:"CN",name:"Wonder Wall",cost:"10",plus:"D",st:"0",hp:"30",img:"wonderwall",rare:"S",keyword:"defensive:neutralizes"});
	Cards.push({id:"B001",type:"C",color:"CF",name:"Ammon",cost:"70",plus:"",st:"30",hp:"30",img:"ammon",rare:"S",keyword:"inspiration:untargetable"});
	Cards.push({id:"B002",type:"C",color:"CF",name:"Angry Mob",cost:"50",plus:"F",st:"20",hp:"30",img:"angrymob",rare:"R",keyword:""});
	Cards.push({id:"B003",type:"C",color:"CF",name:"Uriel",cost:"90",plus:"",st:"40",hp:"40",img:"uriel",rare:"R",keyword:"critical:creature:spell"});
	Cards.push({id:"B004",type:"C",color:"CF",name:"Old Willow",cost:"70",plus:"FF",st:"20",hp:"40",img:"oldwillow",rare:"R",keyword:"defensive"});
	Cards.push({id:"B005",type:"C",color:"CF",name:"Gas Cloud",cost:"45",plus:"",st:"30",hp:"30",img:"gascloud",rare:"N",keyword:"neutralizes"});
	Cards.push({id:"B006",type:"C",color:"CF",name:"Chimera",cost:"80",plus:"F",st:"30",hp:"50",img:"chimera",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"B007",type:"C",color:"CF",name:"King Varan",cost:"100",plus:"",st:"60",hp:"50",img:"kingvaran",rare:"N",keyword:""});
	Cards.push({id:"B008",type:"C",color:"CF",name:"Gladiator",cost:"75",plus:"",st:"40",hp:"40",img:"gladiator",rare:"N",keyword:"critical"});
	Cards.push({id:"B009",type:"C",color:"CF",name:"Creeping Flame",cost:"55",plus:"",st:"30",hp:"50",img:"creepingflame",rare:"N",keyword:"defensive:creature:spell"});
	Cards.push({id:"B010",type:"C",color:"CF",name:"Cait Sith",cost:"50",plus:"",st:"20",hp:"30",img:"caitsith",rare:"N",keyword:"neutralizes:untargetable"});
	Cards.push({id:"B011",type:"C",color:"CF",name:"Conjurer",cost:"45",plus:"",st:"20",hp:"30",img:"conjurer",rare:"S",keyword:"scroll:critical:creature:spell"});
	Cards.push({id:"B012",type:"C",color:"CF",name:"Sulfurous Balloon",cost:"20",plus:"F",st:"10",hp:"40",img:"sulfurousballoon",rare:"R",keyword:""});
	Cards.push({id:"B013",type:"C",color:"CF",name:"Shieldmaiden",cost:"80",plus:"",st:"40",hp:"40",img:"shieldmaiden",rare:"S",keyword:"unyielding"});
	Cards.push({id:"B014",type:"C",color:"CF",name:"General Guan",cost:"65",plus:"F",st:"30",hp:"40",img:"generalguan",rare:"S",keyword:"attacks:first"});
	Cards.push({id:"B015",type:"C",color:"CF",name:"Sigurd",cost:"80",plus:"F",st:"40",hp:"40",img:"sigurd",rare:"S",keyword:"instant:death:neutralizes"});
	Cards.push({id:"B016",type:"C",color:"CF",name:"Sharazad",cost:"50",plus:"",st:"20",hp:"30",img:"sharazad",rare:"S",keyword:"support:creature:spell"});
	Cards.push({id:"B017",type:"C",color:"CF",name:"Shocker",cost:"70",plus:"",st:"10",hp:"40",img:"shocker",rare:"S",keyword:"attacks:first:unyielding"});
	Cards.push({id:"B018",type:"C",color:"CF",name:"Tiamat",cost:"110",plus:"FF",st:"60",hp:"60",img:"tiamat",rare:"R",keyword:"attacks:first:critical:terrain:change"});
	Cards.push({id:"B019",type:"C",color:"CF",name:"Death Scythe",cost:"15",plus:"D",st:"70",hp:"10",img:"deathscythe",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"B020",type:"C",color:"CF",name:"Death Leech",cost:"20",plus:"F",st:"20",hp:"20",img:"deathleech",rare:"R",keyword:"creature:spell"});
	Cards.push({id:"B021",type:"C",color:"CF",name:"Dead Warlord",cost:"60",plus:"D",st:"40",hp:"40",img:"deadwarlord",rare:"S",keyword:"synthesis:boost"});
	Cards.push({id:"B022",type:"C",color:"CF",name:"Doom Devourer",cost:"50",plus:"",st:"30",hp:"30",img:"doomdevourer",rare:"S",keyword:"creature:spell:gain:magic"});
	Cards.push({id:"B023",type:"C",color:"CF",name:"Domovikha",cost:"20",plus:"",st:"10",hp:"20",img:"domovikha",rare:"S",keyword:"creature:spell:enchant:untargetable"});
	Cards.push({id:"B024",type:"C",color:"CF",name:"Knight-errant",cost:"60",plus:"D",st:"40",hp:"30",img:"knighterrant",rare:"R",keyword:"synthesis:neutralizes:reflects"});
	Cards.push({id:"B025",type:"C",color:"CF",name:"Nebiros",cost:"70",plus:"F",st:"50",hp:"40",img:"nebiros",rare:"S",keyword:"draw:critical"});
	Cards.push({id:"B026",type:"C",color:"CF",name:"Ba-al",cost:"40",plus:"FD",st:"50",hp:"50",img:"baal",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"B027",type:"C",color:"CF",name:"Birdmaiden",cost:"65",plus:"",st:"30",hp:"30",img:"birdmaiden",rare:"S",keyword:"unyielding:creature:spell:enchant"});
	Cards.push({id:"B028",type:"C",color:"CF",name:"Burnacle",cost:"70",plus:"",st:"30",hp:"60",img:"burnacle",rare:"N",keyword:"defensive:creature:spell:enchant"});
	Cards.push({id:"B029",type:"C",color:"CF",name:"Burning Titan",cost:"90",plus:"",st:"60",hp:"60",img:"burningtitan",rare:"S",keyword:""});
	Cards.push({id:"B030",type:"C",color:"CF",name:"Hive Queen",cost:"40",plus:"F",st:"20",hp:"40",img:"hivequeen",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"B031",type:"C",color:"CF",name:"Hive Worker",cost:"30",plus:"",st:"20",hp:"20",img:"hiveworker",rare:"S",keyword:""});
	Cards.push({id:"B032",type:"C",color:"CF",name:"Pyroculus",cost:"30",plus:"D",st:"10",hp:"40",img:"pyroculus",rare:"R",keyword:"synthesis:neutralizes:scroll"});
	Cards.push({id:"B033",type:"C",color:"CF",name:"Pyromancer",cost:"70",plus:"",st:"30",hp:"50",img:"pyromancer",rare:"R",keyword:"scroll:attack"});
	Cards.push({id:"B034",type:"C",color:"CF",name:"Valkyria",cost:"70",plus:"F",st:"30",hp:"30",img:"valkyria",rare:"S",keyword:"support:attacks:first"});
	Cards.push({id:"B035",type:"C",color:"CF",name:"Python",cost:"75",plus:"F",st:"40",hp:"50",img:"python",rare:"S",keyword:"penetrates:gain:magic"});
	Cards.push({id:"B036",type:"C",color:"CF",name:"Fire Drake",cost:"80",plus:"",st:"30",hp:"40",img:"firedrake",rare:"S",keyword:""});
	Cards.push({id:"B037",type:"C",color:"CF",name:"Fire Beak",cost:"95",plus:"F",st:"50",hp:"40",img:"firebeak",rare:"R",keyword:"attacks:first:penetrates:critical"});
	Cards.push({id:"B038",type:"C",color:"CF",name:"Fay",cost:"70",plus:"",st:"20",hp:"40",img:"fay",rare:"N",keyword:"scroll:critical:creature:spell"});
	Cards.push({id:"B039",type:"C",color:"CF",name:"Phoenix",cost:"40",plus:"",st:"40",hp:"30",img:"phoenix",rare:"N",keyword:""});
	Cards.push({id:"B040",type:"C",color:"CF",name:"Flame Duke",cost:"60",plus:"FF",st:"50",hp:"50",img:"flameduke",rare:"R",keyword:"attacks:first:critical"});
	Cards.push({id:"B041",type:"C",color:"CF",name:"Phlogiston",cost:"35",plus:"",st:"30",hp:"30",img:"phlogiston",rare:"N",keyword:"critical"});
	Cards.push({id:"B042",type:"C",color:"CF",name:"Hell Pyron",cost:"80",plus:"FFD",st:"70",hp:"60",img:"hellpyron",rare:"R",keyword:"boost:creature:spell:gain:magic"});
	Cards.push({id:"B043",type:"C",color:"CF",name:"Volcanic Dragon",cost:"80",plus:"FF",st:"50",hp:"50",img:"volcanicdragon",rare:"R",keyword:"attacks:first:scroll:attack"});
	Cards.push({id:"B044",type:"C",color:"CF",name:"Minotaur",cost:"60",plus:"",st:"40",hp:"40",img:"minotaur",rare:"N",keyword:""});
	Cards.push({id:"B045",type:"C",color:"CF",name:"Mushussu",cost:"70",plus:"F",st:"40",hp:"50",img:"mushussu",rare:"R",keyword:"inspiration:critical"});
	Cards.push({id:"B046",type:"C",color:"CF",name:"Lavakin",cost:"70",plus:"",st:"60",hp:"30",img:"lavakin",rare:"S",keyword:""});
	Cards.push({id:"B047",type:"C",color:"CF",name:"Red Ogre",cost:"80",plus:"",st:"40",hp:"50",img:"redogre",rare:"N",keyword:""});
	Cards.push({id:"B048",type:"C",color:"CF",name:"Lone Beast",cost:"80",plus:"",st:"20",hp:"40",img:"lonebeast",rare:"S",keyword:"critical"});
	Cards.push({id:"C001",type:"C",color:"CA",name:"Giant Eel",cost:"60",plus:"A",st:"30",hp:"50",img:"gianteel",rare:"N",keyword:"neutralizes"});
	Cards.push({id:"C002",type:"C",color:"CA",name:"Giant Nautilus",cost:"80",plus:"",st:"10",hp:"70",img:"giantnautilus",rare:"N",keyword:""});
	Cards.push({id:"C003",type:"C",color:"CA",name:"Wall of Ice",cost:"25",plus:"",st:"0",hp:"40",img:"wallofice",rare:"N",keyword:"defensive"});
	Cards.push({id:"C004",type:"C",color:"CA",name:"Aqua Duke",cost:"60",plus:"AA",st:"50",hp:"50",img:"aquaduke",rare:"R",keyword:"support:neutralizes"});
	Cards.push({id:"C005",type:"C",color:"CA",name:"Aquahorn",cost:"70",plus:"",st:"50",hp:"30",img:"aquahorn",rare:"N",keyword:"neutralizes:creature:spell"});
	Cards.push({id:"C006",type:"C",color:"CA",name:"Aqualing",cost:"40",plus:"",st:"20",hp:"30",img:"aqualing",rare:"N",keyword:"neutralizes"});
	Cards.push({id:"C007",type:"C",color:"CA",name:"Apsaras",cost:"40",plus:"A",st:"20",hp:"40",img:"apsaras",rare:"S",keyword:"neutralizes"});
	Cards.push({id:"C008",type:"C",color:"CA",name:"Amazon",cost:"70",plus:"",st:"40",hp:"40",img:"amazon",rare:"N",keyword:"gain:magic"});
	Cards.push({id:"C009",type:"C",color:"CA",name:"Alp",cost:"40",plus:"",st:"20",hp:"20",img:"alp",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"C010",type:"C",color:"CA",name:"Undine",cost:"55",plus:"",st:"30",hp:"30",img:"undine",rare:"N",keyword:"neutralizes"});
	Cards.push({id:"C011",type:"C",color:"CA",name:"Amphibian Warrior",cost:"60",plus:"",st:"40",hp:"30",img:"amphibianwarrior",rare:"S",keyword:""});
	Cards.push({id:"C012",type:"C",color:"CA",name:"Yeti",cost:"60",plus:"A",st:"40",hp:"40",img:"yeti",rare:"S",keyword:"instant:death:neutralizes"});
	Cards.push({id:"C013",type:"C",color:"CA",name:"Id",cost:"50",plus:"AD",st:"40",hp:"30",img:"id",rare:"R",keyword:"synthesis:neutralizes:scroll"});
	Cards.push({id:"C014",type:"C",color:"CA",name:"Echinoderm",cost:"70",plus:"",st:"20",hp:"40",img:"echinoderm",rare:"S",keyword:"regenerates:unyielding"});
	Cards.push({id:"C015",type:"C",color:"CA",name:"Otohime",cost:"70",plus:"A",st:"40",hp:"40",img:"otohime",rare:"S",keyword:"boost:enchant"});
	Cards.push({id:"C016",type:"C",color:"CA",name:"Odontotyrannus",cost:"70",plus:"A",st:"50",hp:"50",img:"odontotyrannus",rare:"R",keyword:"inspiration"});
	Cards.push({id:"C017",type:"C",color:"CA",name:"Kaiser Penguin",cost:"90",plus:"",st:"30",hp:"50",img:"kaiserpenguin",rare:"S",keyword:"item:destruction"});
	Cards.push({id:"C018",type:"C",color:"CA",name:"Kawahime",cost:"70",plus:"",st:"30",hp:"40",img:"kawahime",rare:"S",keyword:"unyielding:creature:spell"});
	Cards.push({id:"C019",type:"C",color:"CA",name:"Chironex",cost:"50",plus:"",st:"30",hp:"50",img:"chironex",rare:"S",keyword:"instant:death"});
	Cards.push({id:"C020",type:"C",color:"CA",name:"King Tortoise",cost:"100",plus:"",st:"50",hp:"60",img:"kingtortoise",rare:"N",keyword:"attacks:last"});
	Cards.push({id:"C021",type:"C",color:"CA",name:"Gluey Slug",cost:"60",plus:"",st:"30",hp:"40",img:"glueyslug",rare:"R",keyword:""});
	Cards.push({id:"C022",type:"C",color:"CA",name:"Kelpie",cost:"80",plus:"A",st:"30",hp:"30",img:"kelpie",rare:"S",keyword:""});
	Cards.push({id:"C023",type:"C",color:"CA",name:"Ghost Ship",cost:"75",plus:"",st:"40",hp:"30",img:"ghostship",rare:"S",keyword:"inspiration:neutralizes"});
	Cards.push({id:"C024",type:"C",color:"CA",name:"Sea Bonze",cost:"40",plus:"",st:"10",hp:"40",img:"seabonze",rare:"R",keyword:"defensive"});
	Cards.push({id:"C025",type:"C",color:"CA",name:"Scylla",cost:"60",plus:"A",st:"30",hp:"40",img:"scylla",rare:"R",keyword:"enchant"});
	Cards.push({id:"C026",type:"C",color:"CA",name:"Sludge Titan",cost:"90",plus:"",st:"50",hp:"60",img:"sludgetitan",rare:"S",keyword:"regenerates"});
	Cards.push({id:"C027",type:"C",color:"CA",name:"Swamp Spawn",cost:"20",plus:"",st:"20",hp:"40",img:"swampspawn",rare:"R",keyword:"defensive:creature:spell:enchant"});
	Cards.push({id:"C028",type:"C",color:"CA",name:"Gelatinous Wall",cost:"30",plus:"",st:"10",hp:"50",img:"gelatinouswall",rare:"S",keyword:"defensive:gain:magic"});
	Cards.push({id:"C029",type:"C",color:"CA",name:"Deep-sea Dragon",cost:"80",plus:"AA",st:"50",hp:"50",img:"deepseadragon",rare:"R",keyword:"attacks:first:scroll:attack"});
	Cards.push({id:"C030",type:"C",color:"CA",name:"Tentacles",cost:"70",plus:"A",st:"40",hp:"50",img:"tentacles",rare:"S",keyword:"regenerates:draw"});
	Cards.push({id:"C031",type:"C",color:"CA",name:"Triton",cost:"70",plus:"",st:"30",hp:"40",img:"triton",rare:"N",keyword:"scroll:critical:draw"});
	Cards.push({id:"C032",type:"C",color:"CA",name:"Nessie",cost:"45",plus:"A",st:"20",hp:"40",img:"nessie",rare:"S",keyword:""});
	Cards.push({id:"C033",type:"C",color:"CA",name:"Hyde",cost:"20",plus:"A",st:"30",hp:"30",img:"hyde",rare:"S",keyword:"creature:spell:enchant"});
	Cards.push({id:"C034",type:"C",color:"CA",name:"Bahamut",cost:"110",plus:"AA",st:"60",hp:"60",img:"bahamut",rare:"R",keyword:"attacks:first:terrain:change:regenerates"});
	Cards.push({id:"C035",type:"C",color:"CA",name:"Vigilante",cost:"50",plus:"A",st:"20",hp:"30",img:"vigilante",rare:"R",keyword:""});
	Cards.push({id:"C036",type:"C",color:"CA",name:"Hippocampus",cost:"40",plus:"A",st:"20",hp:"30",img:"hippocampus",rare:"S",keyword:"neutralizes:creature:spell"});
	Cards.push({id:"C037",type:"C",color:"CA",name:"Fate",cost:"60",plus:"",st:"10",hp:"40",img:"fate",rare:"S",keyword:"creature:spell:draw"});
	Cards.push({id:"C038",type:"C",color:"CA",name:"Bloody Pudding",cost:"50",plus:"",st:"20",hp:"20",img:"bloodypudding",rare:"S",keyword:"support"});
	Cards.push({id:"C039",type:"C",color:"CA",name:"Blue Ogre",cost:"80",plus:"",st:"40",hp:"50",img:"blueogre",rare:"N",keyword:""});
	Cards.push({id:"C040",type:"C",color:"CA",name:"Hellgrammite",cost:"60",plus:"A",st:"30",hp:"30",img:"hellgrammite",rare:"R",keyword:""});
	Cards.push({id:"C041",type:"C",color:"CA",name:"Mycoron",cost:"35",plus:"",st:"10",hp:"30",img:"mycoron",rare:"S",keyword:"regenerates"});
	Cards.push({id:"C042",type:"C",color:"CA",name:"Makara",cost:"65",plus:"",st:"30",hp:"40",img:"makara",rare:"R",keyword:"defensive:unyielding:terrain:change"});
	Cards.push({id:"C043",type:"C",color:"CA",name:"Mistwing",cost:"70",plus:"",st:"30",hp:"40",img:"mistwing",rare:"N",keyword:"neutralizes:creature:spell"});
	Cards.push({id:"C044",type:"C",color:"CA",name:"Megalodon",cost:"40",plus:"",st:"50",hp:"50",img:"megalodon",rare:"N",keyword:""});
	Cards.push({id:"C045",type:"C",color:"CA",name:"Rahab",cost:"80",plus:"AAD",st:"60",hp:"60",img:"rahab",rare:"R",keyword:"neutralizes:boost"});
	Cards.push({id:"C046",type:"C",color:"CA",name:"Lizardman",cost:"70",plus:"",st:"30",hp:"40",img:"lizardman",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"C047",type:"C",color:"CA",name:"Lilith",cost:"60",plus:"",st:"0",hp:"30",img:"lilith",rare:"S",keyword:"attacks:first"});
	Cards.push({id:"C048",type:"C",color:"CA",name:"Rune Adept",cost:"50",plus:"A",st:"20",hp:"20",img:"runeadept",rare:"R",keyword:"scroll:critical:untargetable:creature:spell"});
	Cards.push({id:"D001",type:"C",color:"CE",name:"Earth Spirit",cost:"60",plus:"",st:"40",hp:"30",img:"earthspirit",rare:"R",keyword:""});
	Cards.push({id:"D002",type:"C",color:"CE",name:"Unnameable",cost:"30",plus:"ED",st:"50",hp:"10",img:"unnameable",rare:"R",keyword:"instant:death"});
	Cards.push({id:"D003",type:"C",color:"CE",name:"Woodfolk",cost:"75",plus:"",st:"30",hp:"40",img:"woodfolk",rare:"N",keyword:"support"});
	Cards.push({id:"D004",type:"C",color:"CE",name:"Odradek",cost:"40",plus:"",st:"20",hp:"20",img:"odradek",rare:"S",keyword:"support"});
	Cards.push({id:"D005",type:"C",color:"CE",name:"Gargoyle",cost:"70",plus:"E",st:"30",hp:"50",img:"gargoyle",rare:"R",keyword:"attacks:first"});
	Cards.push({id:"D006",type:"C",color:"CE",name:"Cactus Wall",cost:"50",plus:"",st:"10",hp:"50",img:"cactuswall",rare:"S",keyword:"defensive:regenerates"});
	Cards.push({id:"D007",type:"C",color:"CE",name:"Gigantherium",cost:"70",plus:"E",st:"50",hp:"60",img:"gigantherium",rare:"N",keyword:""});
	Cards.push({id:"D008",type:"C",color:"CE",name:"Captain Cock",cost:"50",plus:"E",st:"30",hp:"30",img:"captaincock",rare:"R",keyword:"unyielding:creature:spell"});
	Cards.push({id:"D009",type:"C",color:"CE",name:"Gooba Queen",cost:"25",plus:"E",st:"10",hp:"40",img:"goobaqueen",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"D010",type:"C",color:"CE",name:"Green Ogre",cost:"80",plus:"",st:"40",hp:"50",img:"greenogre",rare:"N",keyword:""});
	Cards.push({id:"D011",type:"C",color:"CE",name:"Grimalkin",cost:"40",plus:"E",st:"20",hp:"30",img:"grimalkin",rare:"R",keyword:"support:untargetable"});
	Cards.push({id:"D012",type:"C",color:"CE",name:"Great Tusker",cost:"80",plus:"E",st:"60",hp:"50",img:"greattusker",rare:"N",keyword:"neutralizes"});
	Cards.push({id:"D013",type:"C",color:"CE",name:"Glowhorn",cost:"50",plus:"E",st:"50",hp:"40",img:"glowhorn",rare:"R",keyword:"inspiration"});
	Cards.push({id:"D014",type:"C",color:"CE",name:"Coatlicue",cost:"70",plus:"E",st:"30",hp:"50",img:"coatlicue",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"D015",type:"C",color:"CE",name:"Cockatrice",cost:"50",plus:"E",st:"30",hp:"40",img:"cockatrice",rare:"S",keyword:""});
	Cards.push({id:"D016",type:"C",color:"CE",name:"Sakuya",cost:"30",plus:"E",st:"20",hp:"30",img:"sakuya",rare:"R",keyword:"creature:spell:terrain:change"});
	Cards.push({id:"D017",type:"C",color:"CE",name:"Jackalope",cost:"60",plus:"",st:"20",hp:"30",img:"jackalope",rare:"S",keyword:"support"});
	Cards.push({id:"D018",type:"C",color:"CE",name:"Shankrubber",cost:"40",plus:"",st:"20",hp:"20",img:"shankrubber",rare:"S",keyword:"untargetable:creature:spell:enchant"});
	Cards.push({id:"D019",type:"C",color:"CE",name:"Sylvan Duchess",cost:"60",plus:"EE",st:"50",hp:"50",img:"sylvanduchess",rare:"R",keyword:"support:item:destruction:regenerates"});
	Cards.push({id:"D020",type:"C",color:"CE",name:"Screamer",cost:"30",plus:"",st:"20",hp:"40",img:"screamer",rare:"S",keyword:"defensive:creature:spell:enchant"});
	Cards.push({id:"D021",type:"C",color:"CE",name:"Squirrine",cost:"50",plus:"",st:"20",hp:"30",img:"squirrine",rare:"N",keyword:"support"});
	Cards.push({id:"D022",type:"C",color:"CE",name:"Wall of Stone",cost:"25",plus:"",st:"0",hp:"60",img:"wallofstone",rare:"N",keyword:"defensive"});
	Cards.push({id:"D023",type:"C",color:"CE",name:"Spitting Cobra",cost:"80",plus:"",st:"40",hp:"40",img:"spittingcobra",rare:"N",keyword:"creature:spell:enchant"});
	Cards.push({id:"D024",type:"C",color:"CE",name:"Sproutling",cost:"60",plus:"",st:"30",hp:"30",img:"sproutling",rare:"R",keyword:"creature:spell"});
	Cards.push({id:"D025",type:"C",color:"CE",name:"Sage",cost:"80",plus:"",st:"20",hp:"30",img:"sage",rare:"N",keyword:"support:scroll:critical"});
	Cards.push({id:"D026",type:"C",color:"CE",name:"Tiger Weta",cost:"60",plus:"",st:"30",hp:"40",img:"tigerweta",rare:"S",keyword:""});
	Cards.push({id:"D027",type:"C",color:"CE",name:"Dusk Dweller",cost:"70",plus:"E",st:"40",hp:"40",img:"duskdweller",rare:"S",keyword:"attacks:first"});
	Cards.push({id:"D028",type:"C",color:"CE",name:"Dragon Zombie",cost:"85",plus:"",st:"40",hp:"60",img:"dragonzombie",rare:"N",keyword:""});
	Cards.push({id:"D029",type:"C",color:"CE",name:"Dryad",cost:"55",plus:"",st:"20",hp:"30",img:"dryad",rare:"N",keyword:"support"});
	Cards.push({id:"D030",type:"C",color:"CE",name:"Dwarven Miner",cost:"70",plus:"E",st:"30",hp:"50",img:"dwarvenminer",rare:"S",keyword:"creature:spell:gain:magic"});
	Cards.push({id:"D031",type:"C",color:"CE",name:"Hardrock Dragon",cost:"80",plus:"EE",st:"50",hp:"50",img:"hardrockdragon",rare:"R",keyword:"attacks:first:creature:spell:damage"});
	Cards.push({id:"D032",type:"C",color:"CE",name:"Barong",cost:"60",plus:"E",st:"30",hp:"40",img:"barong",rare:"S",keyword:""});
	Cards.push({id:"D033",type:"C",color:"CE",name:"Healer",cost:"80",plus:"",st:"10",hp:"40",img:"healer",rare:"S",keyword:"regenerates:unyielding:creature:spell"});
	Cards.push({id:"D034",type:"C",color:"CE",name:"Pixie",cost:"60",plus:"",st:"20",hp:"30",img:"pixie",rare:"S",keyword:"support:unyielding"});
	Cards.push({id:"D035",type:"C",color:"CE",name:"Black Knight",cost:"90",plus:"",st:"40",hp:"40",img:"blackknight",rare:"R",keyword:"critical"});
	Cards.push({id:"D036",type:"C",color:"CE",name:"Branch Army",cost:"80",plus:"E",st:"30",hp:"30",img:"brancharmy",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"D037",type:"C",color:"CE",name:"Brontides",cost:"80",plus:"EED",st:"60",hp:"60",img:"brontides",rare:"R",keyword:"support:boost"});
	Cards.push({id:"D038",type:"C",color:"CE",name:"Mudman",cost:"55",plus:"",st:"20",hp:"40",img:"mudman",rare:"S",keyword:""});
	Cards.push({id:"D039",type:"C",color:"CE",name:"Mummy",cost:"45",plus:"",st:"20",hp:"50",img:"mummy",rare:"N",keyword:"defensive"});
	Cards.push({id:"D040",type:"C",color:"CE",name:"Moss Titan",cost:"65",plus:"",st:"50",hp:"30",img:"mosstitan",rare:"S",keyword:""});
	Cards.push({id:"D041",type:"C",color:"CE",name:"Mormo",cost:"60",plus:"",st:"20",hp:"30",img:"mormo",rare:"S",keyword:"support:inspiration:scroll:critical"});
	Cards.push({id:"D042",type:"C",color:"CE",name:"Jormungandr",cost:"110",plus:"EE",st:"60",hp:"60",img:"jormungandr",rare:"R",keyword:"attacks:first:terrain:change:regenerates"});
	Cards.push({id:"D043",type:"C",color:"CE",name:"Land Urchin",cost:"50",plus:"",st:"20",hp:"50",img:"landurchin",rare:"S",keyword:"defensive"});
	Cards.push({id:"D044",type:"C",color:"CE",name:"Lichenoid",cost:"60",plus:"",st:"30",hp:"30",img:"lichenoid",rare:"N",keyword:"creature:spell"});
	Cards.push({id:"D045",type:"C",color:"CE",name:"Leshy",cost:"40",plus:"",st:"30",hp:"40",img:"leshy",rare:"S",keyword:"defensive"});
	Cards.push({id:"D046",type:"C",color:"CE",name:"Rock Shell",cost:"60",plus:"",st:"40",hp:"30",img:"rockshell",rare:"R",keyword:"creature:spell:enchant"});
	Cards.push({id:"D047",type:"C",color:"CE",name:"Rock Troll",cost:"90",plus:"",st:"50",hp:"50",img:"rocktroll",rare:"N",keyword:"regenerates"});
	Cards.push({id:"D048",type:"C",color:"CE",name:"Werebear",cost:"40",plus:"D",st:"20",hp:"40",img:"werebear",rare:"S",keyword:"synthesis:unyielding"});
	Cards.push({id:"E001",type:"C",color:"CW",name:"Yellow Ogre",cost:"80",plus:"",st:"40",hp:"50",img:"yellowogre",rare:"N",keyword:""});
	Cards.push({id:"E002",type:"C",color:"CW",name:"Witch",cost:"55",plus:"",st:"20",hp:"30",img:"witch",rare:"R",keyword:"scroll:critical:creature:spell:gain:magic"});
	Cards.push({id:"E003",type:"C",color:"CW",name:"Aero Duchess",cost:"60",plus:"WW",st:"50",hp:"50",img:"aeroduchess",rare:"R",keyword:"attacks:first:scroll:critical:creature:spell"});
	Cards.push({id:"E004",type:"C",color:"CW",name:"Elven Archer",cost:"70",plus:"W",st:"40",hp:"40",img:"elvenarcher",rare:"S",keyword:"attacks:first:creature:spell:damage"});
	Cards.push({id:"E005",type:"C",color:"CW",name:"Enchantress",cost:"30",plus:"",st:"10",hp:"20",img:"enchantress",rare:"S",keyword:"scroll:critical"});
	Cards.push({id:"E006",type:"C",color:"CW",name:"Caladrius",cost:"60",plus:"",st:"30",hp:"30",img:"caladrius",rare:"N",keyword:"attacks:first:creature:spell:enchant"});
	Cards.push({id:"E007",type:"C",color:"CW",name:"Garuda",cost:"40",plus:"WW",st:"0",hp:"40",img:"garuda",rare:"R",keyword:""});
	Cards.push({id:"E008",type:"C",color:"CW",name:"Kirin",cost:"80",plus:"",st:"20",hp:"40",img:"kirin",rare:"R",keyword:"attacks:first:inspiration"});
	Cards.push({id:"E009",type:"C",color:"CW",name:"Cu Sith",cost:"70",plus:"",st:"40",hp:"30",img:"cusith",rare:"S",keyword:"inspiration:untargetable"});
	Cards.push({id:"E010",type:"C",color:"CW",name:"Cloud Gizmo",cost:"30",plus:"",st:"10",hp:"30",img:"cloudgizmo",rare:"S",keyword:"creature:spell:card:destruction:draw"});
	Cards.push({id:"E011",type:"C",color:"CW",name:"Griffon",cost:"80",plus:"",st:"50",hp:"50",img:"griffon",rare:"N",keyword:""});
	Cards.push({id:"E012",type:"C",color:"CW",name:"Great Nimbus",cost:"100",plus:"",st:"30",hp:"60",img:"greatnimbus",rare:"N",keyword:"unyielding"});
	Cards.push({id:"E013",type:"C",color:"CW",name:"Gremlin",cost:"60",plus:"",st:"20",hp:"30",img:"gremlin",rare:"S",keyword:"item:destruction"});
	Cards.push({id:"E014",type:"C",color:"CW",name:"Centaur",cost:"80",plus:"",st:"30",hp:"40",img:"centaur",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"E015",type:"C",color:"CW",name:"Cornfolk",cost:"70",plus:"",st:"30",hp:"40",img:"cornfolk",rare:"N",keyword:"gain:magic"});
	Cards.push({id:"E016",type:"C",color:"CW",name:"Serpent Fly",cost:"70",plus:"",st:"40",hp:"30",img:"serpentfly",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"E017",type:"C",color:"CW",name:"Samhain",cost:"50",plus:"D",st:"20",hp:"40",img:"samhain",rare:"R",keyword:"synthesis"});
	Cards.push({id:"E018",type:"C",color:"CW",name:"Thunder Spawn",cost:"50",plus:"W",st:"30",hp:"40",img:"thunderspawn",rare:"R",keyword:""});
	Cards.push({id:"E019",type:"C",color:"CW",name:"Sylph",cost:"30",plus:"",st:"20",hp:"20",img:"sylph",rare:"S",keyword:"neutralizes:creature:spell"});
	Cards.push({id:"E020",type:"C",color:"CW",name:"Scolopendra",cost:"50",plus:"D",st:"30",hp:"40",img:"scolopendra",rare:"R",keyword:"synthesis:enchant"});
	Cards.push({id:"E021",type:"C",color:"CW",name:"Spectre",cost:"30",plus:"",st:"0",hp:"30",img:"spectre",rare:"N",keyword:""});
	Cards.push({id:"E022",type:"C",color:"CW",name:"Sleipnir",cost:"70",plus:"",st:"30",hp:"40",img:"sleipnir",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"E023",type:"C",color:"CW",name:"Soul Collector",cost:"30",plus:"D",st:"20",hp:"30",img:"soulcollector",rare:"S",keyword:""});
	Cards.push({id:"E024",type:"C",color:"CW",name:"Sword Princess",cost:"70",plus:"W",st:"40",hp:"30",img:"swordprincess",rare:"R",keyword:"attacks:first:creature:spell"});
	Cards.push({id:"E025",type:"C",color:"CW",name:"Dhampir",cost:"60",plus:"W",st:"40",hp:"40",img:"dhampir",rare:"S",keyword:"instant:death:neutralizes化"});
	Cards.push({id:"E026",type:"C",color:"CW",name:"Tetrarm",cost:"50",plus:"W",st:"20",hp:"30",img:"tetrarm",rare:"R",keyword:""});
	Cards.push({id:"E027",type:"C",color:"CW",name:"Devastator",cost:"80",plus:"W",st:"50",hp:"40",img:"devastator",rare:"S",keyword:"level:change"});
	Cards.push({id:"E028",type:"C",color:"CW",name:"Dune Titan",cost:"75",plus:"",st:"50",hp:"60",img:"dunetitan",rare:"S",keyword:""});
	Cards.push({id:"E029",type:"C",color:"CW",name:"Typhon",cost:"110",plus:"WW",st:"60",hp:"60",img:"typhon",rare:"R",keyword:"attacks:first:critical:terrain:change"});
	Cards.push({id:"E030",type:"C",color:"CW",name:"Tornado",cost:"55",plus:"",st:"20",hp:"50",img:"tornado",rare:"N",keyword:"defensive:attacks:first"});
	Cards.push({id:"E031",type:"C",color:"CW",name:"Treasure Raider",cost:"90",plus:"",st:"40",hp:"40",img:"treasureraider",rare:"S",keyword:"gain:magic:unyielding"});
	Cards.push({id:"E032",type:"C",color:"CW",name:"Nike",cost:"40",plus:"W",st:"30",hp:"30",img:"nike",rare:"S",keyword:"attacks:first:enchant"});
	Cards.push({id:"E033",type:"C",color:"CW",name:"Knight",cost:"90",plus:"",st:"50",hp:"40",img:"knight",rare:"N",keyword:"critical"});
	Cards.push({id:"E034",type:"C",color:"CW",name:"Nightmare",cost:"40",plus:"W",st:"30",hp:"30",img:"nightmare",rare:"S",keyword:"penetrates"});
	Cards.push({id:"E035",type:"C",color:"CW",name:"Powder Eater",cost:"10",plus:"",st:"1",hp:"1",img:"powdereater",rare:"S",keyword:""});
	Cards.push({id:"E036",type:"C",color:"CW",name:"Patronus",cost:"30",plus:"W",st:"30",hp:"20",img:"patronus",rare:"R",keyword:"untargetable:creature:spell:enchant"});
	Cards.push({id:"E037",type:"C",color:"CW",name:"Breeze Spirit",cost:"50",plus:"",st:"20",hp:"30",img:"breezespirit",rare:"S",keyword:""});
	Cards.push({id:"E038",type:"C",color:"CW",name:"Blitz Raven",cost:"30",plus:"",st:"30",hp:"20",img:"blitzraven",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"E039",type:"C",color:"CW",name:"Pulgasari",cost:"90",plus:"",st:"40",hp:"40",img:"pulgasari",rare:"S",keyword:""});
	Cards.push({id:"E040",type:"C",color:"CW",name:"Holy Llama",cost:"60",plus:"",st:"20",hp:"40",img:"holyllama",rare:"S",keyword:"creature:spell:enchant"});
	Cards.push({id:"E041",type:"C",color:"CW",name:"Martial Monk",cost:"70",plus:"D",st:"20",hp:"50",img:"martialmonk",rare:"S",keyword:"synthesis:attacks:first:unyielding"});
	Cards.push({id:"E042",type:"C",color:"CW",name:"Mad Harlequin",cost:"50",plus:"",st:"20",hp:"40",img:"madharlequin",rare:"S",keyword:"boost:unyielding"});
	Cards.push({id:"E043",type:"C",color:"CW",name:"Yowie",cost:"70",plus:"",st:"40",hp:"40",img:"yowie",rare:"N",keyword:"critical"});
	Cards.push({id:"E044",type:"C",color:"CW",name:"Lightning Dragon",cost:"80",plus:"WW",st:"50",hp:"50",img:"lightningdragon",rare:"R",keyword:"attacks:first:creature:spell:damage"});
	Cards.push({id:"E045",type:"C",color:"CW",name:"Rokh",cost:"60",plus:"W",st:"40",hp:"50",img:"rokh",rare:"S",keyword:"inspiration"});
	Cards.push({id:"E046",type:"C",color:"CW",name:"Lemures",cost:"30",plus:"W",st:"20",hp:"30",img:"lemures",rare:"R",keyword:"creature:spell:card:destruction"});
	Cards.push({id:"E047",type:"C",color:"CW",name:"Lord of Bane",cost:"80",plus:"WWD",st:"70",hp:"60",img:"lordofbane",rare:"R",keyword:"boost:creature:spell"});
	Cards.push({id:"E048",type:"C",color:"CW",name:"Wyvern",cost:"60",plus:"W",st:"40",hp:"40",img:"wyvern",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"G001",type:"I",color:"IT",name:"Argent Key",cost:"70",plus:"",st:"",hp:"",img:"argentkey",rare:"R",keyword:"attacks:first"});
	Cards.push({id:"G002",type:"I",color:"IT",name:"Armet",cost:"45",plus:"",st:"",hp:"",img:"armet",rare:"N",keyword:""});
	Cards.push({id:"G003",type:"I",color:"IT",name:"Angry Mask",cost:"60",plus:"",st:"",hp:"",img:"angrymask",rare:"R",keyword:""});
	Cards.push({id:"G004",type:"I",color:"IP",name:"Eagle Rapier",cost:"40",plus:"",st:"",hp:"",img:"eaglerapier",rare:"S",keyword:"attacks:first"});
	Cards.push({id:"G005",type:"I",color:"IT",name:"Warlock's Disk",cost:"110",plus:"",st:"",hp:"",img:"warlocksdisk",rare:"R",keyword:""});
	Cards.push({id:"G006",type:"I",color:"IO",name:"Eternal Mail",cost:"40",plus:"",st:"",hp:"",img:"eternalmail",rare:"R",keyword:""});
	Cards.push({id:"G007",type:"I",color:"IO",name:"Angel Cape",cost:"50",plus:"",st:"",hp:"",img:"angelcape",rare:"R",keyword:""});
	Cards.push({id:"G008",type:"I",color:"IR",name:"Aura Strike",cost:"90",plus:"",st:"",hp:"",img:"aurastrike",rare:"R",keyword:"scroll:attack"});
	Cards.push({id:"G009",type:"I",color:"IP",name:"Catapult",cost:"50",plus:"",st:"",hp:"",img:"catapult",rare:"N",keyword:""});
	Cards.push({id:"G010",type:"I",color:"IP",name:"Claymore",cost:"50",plus:"",st:"",hp:"",img:"claymore",rare:"R",keyword:""});
	Cards.push({id:"G011",type:"I",color:"IT",name:"Gremlin's Eye",cost:"80",plus:"",st:"",hp:"",img:"gremlinseye",rare:"R",keyword:"item:destruction"});
	Cards.push({id:"G012",type:"I",color:"IT",name:"Golden Goose",cost:"0",plus:"",st:"",hp:"",img:"goldengoose",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"G013",type:"I",color:"IP",name:"Golden Hammer",cost:"50",plus:"",st:"",hp:"",img:"goldenhammer",rare:"N",keyword:"gain:magic"});
	Cards.push({id:"G014",type:"I",color:"IT",name:"Ring of the Succubus",cost:"30",plus:"",st:"",hp:"",img:"ringofthesuccubus",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"G015",type:"I",color:"IP",name:"Claw of Shade",cost:"90",plus:"",st:"",hp:"",img:"clawofshade",rare:"R",keyword:""});
	Cards.push({id:"G016",type:"I",color:"IR",name:"Shadow Blaze",cost:"70",plus:"",st:"",hp:"",img:"shadowblaze",rare:"S",keyword:"scroll:attack:scroll:critical"});
	Cards.push({id:"G017",type:"I",color:"IT",name:"Silver Plow",cost:"30",plus:"",st:"",hp:"",img:"silverplow",rare:"S",keyword:""});
	Cards.push({id:"G018",type:"I",color:"IO",name:"Squid Mantle",cost:"50",plus:"",st:"",hp:"",img:"squidmantle",rare:"R",keyword:""});
	Cards.push({id:"G019",type:"I",color:"IO",name:"Scale Armor",cost:"30",plus:"",st:"",hp:"",img:"scalearmor",rare:"N",keyword:""});
	Cards.push({id:"G020",type:"I",color:"IO",name:"Storm Armor",cost:"70",plus:"",st:"",hp:"",img:"stormarmor",rare:"R",keyword:""});
	Cards.push({id:"G021",type:"I",color:"IP",name:"Stormcauser",cost:"55",plus:"",st:"",hp:"",img:"stormcauser",rare:"R",keyword:""});
	Cards.push({id:"G022",type:"I",color:"IO",name:"Storm Shield",cost:"70",plus:"",st:"",hp:"",img:"stormshield",rare:"S",keyword:"neutralizes"});
	Cards.push({id:"G023",type:"I",color:"IP",name:"Storm Spear",cost:"20",plus:"",st:"",hp:"",img:"stormspear",rare:"N",keyword:"critical"});
	Cards.push({id:"G024",type:"I",color:"IP",name:"Storm Halberd",cost:"70",plus:"",st:"",hp:"",img:"stormhalberd",rare:"S",keyword:"critical"});
	Cards.push({id:"G025",type:"I",color:"IR",name:"Spark Ball",cost:"60",plus:"",st:"",hp:"",img:"sparkball",rare:"N",keyword:"scroll:attack"});
	Cards.push({id:"G026",type:"I",color:"IO",name:"Spiked Shield",cost:"40",plus:"",st:"",hp:"",img:"spikedshield",rare:"S",keyword:"neutralizes"});
	Cards.push({id:"G027",type:"I",color:"IO",name:"Sphere Shield",cost:"100",plus:"",st:"",hp:"",img:"sphereshield",rare:"S",keyword:"neutralizes"});
	Cards.push({id:"G028",type:"I",color:"IO",name:"Spectre's Robe",cost:"60",plus:"",st:"",hp:"",img:"spectresrobe",rare:"N",keyword:""});
	Cards.push({id:"G029",type:"I",color:"IT",name:"Sling",cost:"30",plus:"",st:"",hp:"",img:"sling",rare:"N",keyword:"attacks:first"});
	Cards.push({id:"G030",type:"I",color:"IO",name:"Gelatinous Wall",cost:"50",plus:"",st:"",hp:"",img:"gelatinousarmor",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"G031",type:"I",color:"IR",name:"Soul Ray",cost:"70",plus:"",st:"",hp:"",img:"soulray",rare:"S",keyword:"scroll:attack"});
	Cards.push({id:"G032",type:"I",color:"IT",name:"Turquoise Amulet",cost:"50",plus:"",st:"",hp:"",img:"turquoiseamulet",rare:"R",keyword:"instant:death:neutralizes"});
	Cards.push({id:"G033",type:"I",color:"IO",name:"Diamond Armor",cost:"60",plus:"",st:"",hp:"",img:"diamondarmor",rare:"S",keyword:""});
	Cards.push({id:"G034",type:"I",color:"IO",name:"Chain Mail",cost:"10",plus:"",st:"",hp:"",img:"chainmail",rare:"N",keyword:""});
	Cards.push({id:"G035",type:"I",color:"IP",name:"Chain Saw",cost:"50",plus:"",st:"",hp:"",img:"chainsaw",rare:"S",keyword:""});
	Cards.push({id:"G036",type:"I",color:"IR",name:"Chilling Blast",cost:"90",plus:"",st:"",hp:"",img:"chillingblast",rare:"R",keyword:"scroll:attack:scroll:critical"});
	Cards.push({id:"G037",type:"I",color:"IT",name:"Twin Spike",cost:"30",plus:"",st:"",hp:"",img:"twinspike",rare:"S",keyword:""});
	Cards.push({id:"G038",type:"I",color:"IR",name:"Tearing Halo",cost:"60",plus:"",st:"",hp:"",img:"tearinghalo",rare:"S",keyword:"scroll:attack"});
	Cards.push({id:"G039",type:"I",color:"IT",name:"Tombstone",cost:"0",plus:"",st:"",hp:"",img:"tombstone",rare:"S",keyword:"draw"});
	Cards.push({id:"G040",type:"I",color:"IT",name:"Topaz Amulet",cost:"50",plus:"",st:"",hp:"",img:"topazamulet",rare:"R",keyword:"instant:death:neutralizes"});
	Cards.push({id:"G041",type:"I",color:"IP",name:"Trident",cost:"50",plus:"",st:"",hp:"",img:"trident",rare:"N",keyword:""});
	Cards.push({id:"G042",type:"I",color:"IT",name:"Dragon Orb",cost:"50",plus:"",st:"",hp:"",img:"dragonorb",rare:"S",keyword:""});
	Cards.push({id:"G043",type:"I",color:"IP",name:"Drill Lance",cost:"50",plus:"",st:"",hp:"",img:"drilllance",rare:"S",keyword:"penetrates"});
	Cards.push({id:"G044",type:"I",color:"IP",name:"Tonfa",cost:"30",plus:"",st:"",hp:"",img:"tonfa",rare:"S",keyword:""});
	Cards.push({id:"G045",type:"I",color:"IP",name:"Napalm Arrow",cost:"50",plus:"",st:"",hp:"",img:"napalmarrow",rare:"S",keyword:""});
	Cards.push({id:"G046",type:"I",color:"IO",name:"Neutral Cloak",cost:"50",plus:"",st:"",hp:"",img:"neutralcloak",rare:"S",keyword:""});
	Cards.push({id:"G047",type:"I",color:"IT",name:"Necro Scarab",cost:"60",plus:"",st:"",hp:"",img:"necroscarab",rare:"S",keyword:""});
	Cards.push({id:"G048",type:"I",color:"IR",name:"Necro Plasma",cost:"70",plus:"",st:"",hp:"",img:"necroplasma",rare:"S",keyword:"scroll:attack"});
	Cards.push({id:"G049",type:"I",color:"IT",name:"Burning Heart",cost:"70",plus:"",st:"",hp:"",img:"burningheart",rare:"S",keyword:""});
	Cards.push({id:"G050",type:"I",color:"IR",name:"Burning Rod",cost:"90",plus:"",st:"",hp:"",img:"burningrod",rare:"R",keyword:"scroll:attack:scroll:critical"});
	Cards.push({id:"G051",type:"I",color:"IP",name:"Binding Whip",cost:"30",plus:"",st:"",hp:"",img:"bindingwhip",rare:"N",keyword:"enchant"});
	Cards.push({id:"G052",type:"I",color:"IP",name:"Battering Ram",cost:"40",plus:"",st:"",hp:"",img:"batteringram",rare:"N",keyword:"instant:death"});
	Cards.push({id:"G053",type:"I",color:"IO",name:"Buckler",cost:"20",plus:"",st:"",hp:"",img:"buckler",rare:"N",keyword:"neutralizes"});
	Cards.push({id:"G054",type:"I",color:"IP",name:"Battle Axe",cost:"30",plus:"",st:"",hp:"",img:"battleaxe",rare:"N",keyword:""});
	Cards.push({id:"G055",type:"I",color:"IP",name:"Boomerang",cost:"50",plus:"",st:"",hp:"",img:"boomerang",rare:"S",keyword:""});
	Cards.push({id:"G056",type:"I",color:"IT",name:"Force Anklet",cost:"70",plus:"",st:"",hp:"",img:"forceanklet",rare:"S",keyword:""});
	Cards.push({id:"G057",type:"I",color:"IP",name:"Sword of Pluck",cost:"40",plus:"",st:"",hp:"",img:"swordofpluck",rare:"N",keyword:"critical"});
	Cards.push({id:"G058",type:"I",color:"IP",name:"Prismatic Wand",cost:"70",plus:"",st:"",hp:"",img:"prismaticwand",rare:"S",keyword:""});
	Cards.push({id:"G059",type:"I",color:"IO",name:"Plate Mail",cost:"50",plus:"",st:"",hp:"",img:"platemail",rare:"S",keyword:""});
	Cards.push({id:"G060",type:"I",color:"IT",name:"Petrify Stone",cost:"20",plus:"",st:"",hp:"",img:"petrifystone",rare:"N",keyword:""});
	Cards.push({id:"G061",type:"I",color:"IP",name:"Vorpal Sword",cost:"60",plus:"",st:"",hp:"",img:"vorpalsword",rare:"R",keyword:"critical"});
	Cards.push({id:"G062",type:"I",color:"IO",name:"Magma Armor",cost:"70",plus:"",st:"",hp:"",img:"magmaarmor",rare:"R",keyword:""});
	Cards.push({id:"G063",type:"I",color:"IO",name:"Magma Shield",cost:"70",plus:"",st:"",hp:"",img:"magmashield",rare:"S",keyword:"neutralizes"});
	Cards.push({id:"G064",type:"I",color:"IP",name:"Magma Hammer",cost:"20",plus:"",st:"",hp:"",img:"magmahammer",rare:"N",keyword:"critical"});
	Cards.push({id:"G065",type:"I",color:"IP",name:"Magma Flail",cost:"70",plus:"",st:"",hp:"",img:"magmaflail",rare:"S",keyword:"critical"});
	Cards.push({id:"G066",type:"I",color:"IO",name:"Magic Shield",cost:"20",plus:"",st:"",hp:"",img:"magicshield",rare:"N",keyword:"neutralizes:scroll"});
	Cards.push({id:"G067",type:"I",color:"IO",name:"Mirror Hoplon",cost:"50",plus:"",st:"",hp:"",img:"mirrorhoplon",rare:"S",keyword:"neutralizes::scroll"});
	Cards.push({id:"G068",type:"I",color:"IP",name:"Moon Scimitar",cost:"30",plus:"",st:"",hp:"",img:"moonscimitar",rare:"N",keyword:"enchant"});
	Cards.push({id:"G069",type:"I",color:"IP",name:"Murasame",cost:"80",plus:"",st:"",hp:"",img:"murasame",rare:"R",keyword:""});
	Cards.push({id:"G070",type:"I",color:"IT",name:"Magus's Mirror",cost:"30",plus:"",st:"",hp:"",img:"magussmirror",rare:"S",keyword:"neutralizes:scroll"});
	Cards.push({id:"G071",type:"I",color:"IP",name:"Mace",cost:"0",plus:"",st:"",hp:"",img:"mace",rare:"N",keyword:""});
	Cards.push({id:"G072",type:"I",color:"IT",name:"Rag Doll",cost:"60",plus:"",st:"",hp:"",img:"ragdoll",rare:"S",keyword:"neutralizes:scroll:neutralizes"});
	Cards.push({id:"G073",type:"I",color:"IO",name:"Reactive Armor",cost:"50",plus:"",st:"",hp:"",img:"reactivearmor",rare:"R",keyword:""});
	Cards.push({id:"G074",type:"I",color:"IP",name:"Long Sword",cost:"10",plus:"",st:"",hp:"",img:"longsword",rare:"N",keyword:""});
	Cards.push({id:"G075",type:"I",color:"IT",name:"Wonder Charm",cost:"70",plus:"",st:"",hp:"",img:"wondercharm",rare:"S",keyword:"neutralizes"});
	Cards.push({id:"H001",type:"S",color:"SG",name:"Earth Shift",cost:"100",plus:"",st:"",hp:"",img:"earthshift",rare:"N",keyword:"terrain:change"});
	Cards.push({id:"H002",type:"S",color:"SG",name:"Outrage",cost:"100",plus:"",st:"",hp:"",img:"outrage",rare:"S",keyword:""});
	Cards.push({id:"H003",type:"S",color:"SG",name:"Asteroid",cost:"100",plus:"D",st:"",hp:"",img:"asteroid",rare:"R",keyword:"level:change:synthesis"});
	Cards.push({id:"H004",type:"S",color:"SG",name:"Assemble Cards",cost:"70",plus:"",st:"",hp:"",img:"assemblecards",rare:"S",keyword:"secret:gain:magic:draw"});
	Cards.push({id:"H005",type:"S",color:"SL",name:"Alarm",cost:"70",plus:"",st:"",hp:"",img:"alarm",rare:"R",keyword:""});
	Cards.push({id:"H006",type:"S",color:"SY",name:"Immobilize",cost:"80",plus:"",st:"",hp:"",img:"immobilize",rare:"R",keyword:""});
	Cards.push({id:"H007",type:"S",color:"SG",name:"Incineration",cost:"10",plus:"",st:"",hp:"",img:"incineration",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H008",type:"S",color:"SG",name:"Influence",cost:"80",plus:"",st:"",hp:"",img:"influence",rare:"S",keyword:"terrain:change"});
	Cards.push({id:"H009",type:"S",color:"SZ",name:"Waste World",cost:"70",plus:"",st:"",hp:"",img:"wasteworld",rare:"S",keyword:""});
	Cards.push({id:"H010",type:"S",color:"SG",name:"Water Shift",cost:"100",plus:"",st:"",hp:"",img:"watershift",rare:"N",keyword:"terrain:change"});
	Cards.push({id:"H011",type:"S",color:"SG",name:"Air Shift",cost:"100",plus:"",st:"",hp:"",img:"airshift",rare:"N",keyword:"terrain:change"});
	Cards.push({id:"H012",type:"S",color:"SG",name:"Exile",cost:"100",plus:"",st:"",hp:"",img:"exile",rare:"S",keyword:""});
	Cards.push({id:"H013",type:"S",color:"SG",name:"Exchange",cost:"60",plus:"",st:"",hp:"",img:"exchange",rare:"S",keyword:""});
	Cards.push({id:"H014",type:"S",color:"SG",name:"Escape",cost:"20",plus:"",st:"",hp:"",img:"escape",rare:"N",keyword:"movement"});
	Cards.push({id:"H015",type:"S",color:"SX",name:"Energy Field",cost:"60",plus:"",st:"",hp:"",img:"energyfield",rare:"S",keyword:"neutralizes:gain:magic"});
	Cards.push({id:"H016",type:"S",color:"SL",name:"Elemental Wrath",cost:"70",plus:"",st:"",hp:"",img:"elementalwrath",rare:"N",keyword:"damage"});
	Cards.push({id:"H017",type:"S",color:"SL",name:"Erosion",cost:"40",plus:"D",st:"",hp:"",img:"erosion",rare:"R",keyword:"card:destruction"});
	Cards.push({id:"H018",type:"S",color:"SL",name:"Obliteration",cost:"80",plus:"",st:"",hp:"",img:"obliteration",rare:"R",keyword:""});
	Cards.push({id:"H019",type:"S",color:"SY",name:"Chaos Panic",cost:"60",plus:"",st:"",hp:"",img:"chaospanic",rare:"S",keyword:"movement"});
	Cards.push({id:"H020",type:"S",color:"SG",name:"Gift",cost:"100",plus:"",st:"",hp:"",img:"gift",rare:"S",keyword:"gain:magic:draw"});
	Cards.push({id:"H021",type:"S",color:"SX",name:"Quicksand",cost:"100",plus:"",st:"",hp:"",img:"quicksand",rare:"R",keyword:""});
	Cards.push({id:"H022",type:"S",color:"SG",name:"Quintessence",cost:"80",plus:"",st:"",hp:"",img:"quintessence",rare:"R",keyword:"terrain:change"});
	Cards.push({id:"H023",type:"S",color:"SL",name:"Cluster Burst",cost:"90",plus:"",st:"",hp:"",img:"clusterburst",rare:"S",keyword:"damage"});
	Cards.push({id:"H024",type:"S",color:"SX",name:"Greed",cost:"30",plus:"",st:"",hp:"",img:"greed",rare:"N",keyword:"draw"});
	Cards.push({id:"H025",type:"S",color:"SG",name:"Clairvoyance",cost:"20",plus:"",st:"",hp:"",img:"clairvoyance",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H026",type:"S",color:"SG",name:"Growth Body",cost:"20",plus:"",st:"",hp:"",img:"growthbody",rare:"N",keyword:""});
	Cards.push({id:"H027",type:"S",color:"SY",name:"Quietude",cost:"70",plus:"",st:"",hp:"",img:"quietude",rare:"S",keyword:""});
	Cards.push({id:"H028",type:"S",color:"SG",name:"Goblin's Lair",cost:"10",plus:"D",st:"",hp:"",img:"goblinslair",rare:"S",keyword:""});
	Cards.push({id:"H029",type:"S",color:"SG",name:"Sudden Impact",cost:"100",plus:"",st:"",hp:"",img:"suddenimpact",rare:"S",keyword:"secret:level:change"});
	Cards.push({id:"H030",type:"S",color:"SG",name:"Subsidence",cost:"100",plus:"D",st:"",hp:"",img:"subsidence",rare:"R",keyword:"level:change"});
	Cards.push({id:"H031",type:"S",color:"SG",name:"Thunderclap",cost:"100",plus:"",st:"",hp:"",img:"thunderclap",rare:"S",keyword:"secret:damage"});
	Cards.push({id:"H032",type:"S",color:"SX",name:"Senility",cost:"100",plus:"",st:"",hp:"",img:"senility",rare:"R",keyword:""});
	Cards.push({id:"H033",type:"S",color:"SG",name:"Shining Geyser",cost:"100",plus:"D",st:"",hp:"",img:"shininggeyser",rare:"R",keyword:"damage:synthesis"});
	Cards.push({id:"H034",type:"S",color:"SG",name:"Shatter",cost:"30",plus:"",st:"",hp:"",img:"shatter",rare:"N",keyword:"card:destruction"});
	Cards.push({id:"H035",type:"S",color:"SX",name:"Sigil of Shrink",cost:"40",plus:"",st:"",hp:"",img:"sigilofshrink",rare:"S",keyword:"creature:spell"});
	Cards.push({id:"H036",type:"S",color:"SZ",name:"Joint World",cost:"50",plus:"",st:"",hp:"",img:"jointworld",rare:"R",keyword:""});
	Cards.push({id:"H037",type:"S",color:"SL",name:"Insect Swarm",cost:"120",plus:"",st:"",hp:"",img:"insectswarm",rare:"R",keyword:"damage"});
	Cards.push({id:"H038",type:"S",color:"SG",name:"Squeeze",cost:"50",plus:"",st:"",hp:"",img:"squeeze",rare:"N",keyword:"card:destruction:gain:magic"});
	Cards.push({id:"H039",type:"S",color:"SG",name:"Steal Gem",cost:"40",plus:"",st:"",hp:"",img:"stealgem",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H040",type:"S",color:"SG",name:"Storm Shift",cost:"120",plus:"",st:"",hp:"",img:"stormshift",rare:"S",keyword:"terrain:change"});
	Cards.push({id:"H041",type:"S",color:"SG",name:"Stone Blast",cost:"80",plus:"",st:"",hp:"",img:"stoneblast",rare:"S",keyword:"damage"});
	Cards.push({id:"H042",type:"S",color:"SG",name:"Sneak Hand",cost:"100",plus:"",st:"",hp:"",img:"sneakhand",rare:"R",keyword:"secret:card:destruction"});
	Cards.push({id:"H043",type:"S",color:"SG",name:"Spartoi",cost:"30",plus:"D",st:"",hp:"",img:"spartoi",rare:"N",keyword:""});
	Cards.push({id:"H044",type:"S",color:"SG",name:"Speed Penalty",cost:"70",plus:"",st:"",hp:"",img:"speedpenalty",rare:"N",keyword:"gain:magic"});
	Cards.push({id:"H045",type:"S",color:"SX",name:"Spirit Walk",cost:"20",plus:"",st:"",hp:"",img:"spiritwalk",rare:"N",keyword:""});
	Cards.push({id:"H046",type:"S",color:"SG",name:"Thrust Blow",cost:"70",plus:"",st:"",hp:"",img:"thrustblow",rare:"R",keyword:""});
	Cards.push({id:"H047",type:"S",color:"SG",name:"Theft",cost:"100",plus:"",st:"",hp:"",img:"theft",rare:"R",keyword:"card:destruction"});
	Cards.push({id:"H048",type:"S",color:"SZ",name:"Solid World",cost:"70",plus:"",st:"",hp:"",img:"solidworld",rare:"R",keyword:""});
	Cards.push({id:"H049",type:"S",color:"SZ",name:"Dark World",cost:"70",plus:"",st:"",hp:"",img:"darkworld",rare:"R",keyword:"untargetable"});
	Cards.push({id:"H050",type:"S",color:"SG",name:"Turn to the Wall",cost:"80",plus:"",st:"",hp:"",img:"turntothewall",rare:"R",keyword:""});
	Cards.push({id:"H051",type:"S",color:"SG",name:"Tiny Army",cost:"100",plus:"",st:"",hp:"",img:"tinyarmy",rare:"R",keyword:"secret:gain:magic"});
	Cards.push({id:"H052",type:"S",color:"SX",name:"Charging Step",cost:"20",plus:"",st:"",hp:"",img:"chargingstep",rare:"N",keyword:"movement:gain:magic"});
	Cards.push({id:"H053",type:"S",color:"SG",name:"Chariot",cost:"50",plus:"",st:"",hp:"",img:"chariot",rare:"S",keyword:""});
	Cards.push({id:"H054",type:"S",color:"SL",name:"Disaster",cost:"120",plus:"D",st:"",hp:"",img:"disaster",rare:"R",keyword:"damage"});
	Cards.push({id:"H055",type:"S",color:"SX",name:"Disease",cost:"30",plus:"",st:"",hp:"",img:"disease",rare:"N",keyword:"draw"});
	Cards.push({id:"H056",type:"S",color:"SX",name:"Diselement",cost:"20",plus:"D",st:"",hp:"",img:"diselement",rare:"S",keyword:"synthesis"});
	Cards.push({id:"H057",type:"S",color:"SL",name:"Discord",cost:"80",plus:"D",st:"",hp:"",img:"discord",rare:"S",keyword:""});
	Cards.push({id:"H058",type:"S",color:"SY",name:"Tyranny",cost:"100",plus:"D",st:"",hp:"",img:"tyranny",rare:"R",keyword:""});
	Cards.push({id:"H059",type:"S",color:"SG",name:"Debility",cost:"40",plus:"D",st:"",hp:"",img:"debility",rare:"S",keyword:"synthesis:draw"});
	Cards.push({id:"H060",type:"S",color:"SG",name:"Temptation",cost:"70",plus:"D",st:"",hp:"",img:"temptation",rare:"R",keyword:"creature:spell"});
	Cards.push({id:"H061",type:"S",color:"SX",name:"Dominant Growth",cost:"50",plus:"",st:"",hp:"",img:"dominantgrowth",rare:"R",keyword:""});
	Cards.push({id:"H062",type:"S",color:"SX",name:"Dream Terrain",cost:"40",plus:"",st:"",hp:"",img:"dreamterrain",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H063",type:"S",color:"SX",name:"Sigil of Drain",cost:"20",plus:"",st:"",hp:"",img:"sigilofdrain",rare:"R",keyword:"creature:spell:gain:magic"});
	Cards.push({id:"H064",type:"S",color:"SG",name:"Drain Magic",cost:"80",plus:"",st:"",hp:"",img:"drainmagic",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H065",type:"S",color:"SZ",name:"Natural World",cost:"70",plus:"",st:"",hp:"",img:"naturalworld",rare:"R",keyword:""});
	Cards.push({id:"H066",type:"S",color:"SL",name:"Burning Hail",cost:"100",plus:"",st:"",hp:"",img:"burninghail",rare:"R",keyword:"damage"});
	Cards.push({id:"H067",type:"S",color:"SX",name:"Vitality",cost:"30",plus:"",st:"",hp:"",img:"vitality",rare:"N",keyword:"draw"});
	Cards.push({id:"H068",type:"S",color:"SX",name:"Hyperactive",cost:"40",plus:"",st:"",hp:"",img:"hyperactive",rare:"S",keyword:"unyielding"});
	Cards.push({id:"H069",type:"S",color:"SX",name:"Binding Mist",cost:"40",plus:"",st:"",hp:"",img:"bindingmist",rare:"S",keyword:""});
	Cards.push({id:"H070",type:"S",color:"SX",name:"Bounty Hunt",cost:"50",plus:"",st:"",hp:"",img:"bountyhunt",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H071",type:"S",color:"SY",name:"Pacifism",cost:"70",plus:"",st:"",hp:"",img:"pacifism",rare:"N",keyword:""});
	Cards.push({id:"H072",type:"S",color:"SX",name:"Barrier",cost:"30",plus:"",st:"",hp:"",img:"barrier",rare:"N",keyword:"untargetable"});
	Cards.push({id:"H073",type:"S",color:"SX",name:"Peace",cost:"80",plus:"",st:"",hp:"",img:"peace",rare:"R",keyword:""});
	Cards.push({id:"H074",type:"S",color:"SL",name:"Purify",cost:"20",plus:"",st:"",hp:"",img:"purify",rare:"N",keyword:"gain:magic"});
	Cards.push({id:"H075",type:"S",color:"SG",name:"Fire Shift",cost:"100",plus:"",st:"",hp:"",img:"fireshift",rare:"N",keyword:"terrain:change"});
	Cards.push({id:"H076",type:"S",color:"SG",name:"Fat Body",cost:"40",plus:"",st:"",hp:"",img:"fatbody",rare:"S",keyword:""});
	Cards.push({id:"H077",type:"S",color:"SG",name:"Fear",cost:"100",plus:"",st:"",hp:"",img:"fear",rare:"R",keyword:""});
	Cards.push({id:"H078",type:"S",color:"SG",name:"Philosophy",cost:"50",plus:"",st:"",hp:"",img:"philosophy",rare:"S",keyword:"draw"});
	Cards.push({id:"H079",type:"S",color:"SG",name:"Foresight",cost:"30",plus:"",st:"",hp:"",img:"foresight",rare:"S",keyword:"draw"});
	Cards.push({id:"H080",type:"S",color:"SG",name:"Form Portal",cost:"140",plus:"",st:"",hp:"",img:"formportal",rare:"R",keyword:"movement"});
	Cards.push({id:"H081",type:"S",color:"SG",name:"Fly",cost:"50",plus:"",st:"",hp:"",img:"fly",rare:"N",keyword:"movement"});
	Cards.push({id:"H082",type:"S",color:"SZ",name:"Bright World",cost:"70",plus:"",st:"",hp:"",img:"brightworld",rare:"R",keyword:""});
	Cards.push({id:"H083",type:"S",color:"SG",name:"Fluxion",cost:"100",plus:"",st:"",hp:"",img:"fluxion",rare:"R",keyword:"secret:gain:magic"});
	Cards.push({id:"H084",type:"S",color:"SX",name:"Blast Trap",cost:"30",plus:"",st:"",hp:"",img:"blasttrap",rare:"S",keyword:""});
	Cards.push({id:"H085",type:"S",color:"SX",name:"Blackout",cost:"40",plus:"",st:"",hp:"",img:"blackout",rare:"N",keyword:""});
	Cards.push({id:"H086",type:"S",color:"SL",name:"Flatland",cost:"100",plus:"",st:"",hp:"",img:"flatland",rare:"S",keyword:"secret:gain:magic"});
	Cards.push({id:"H087",type:"S",color:"SL",name:"Freeze Cyclone",cost:"100",plus:"",st:"",hp:"",img:"freezecyclone",rare:"R",keyword:"damage"});
	Cards.push({id:"H088",type:"S",color:"SY",name:"Plague",cost:"100",plus:"",st:"",hp:"",img:"plague",rare:"S",keyword:""});
	Cards.push({id:"H089",type:"S",color:"SG",name:"Blaze Splash",cost:"80",plus:"",st:"",hp:"",img:"blazesplash",rare:"S",keyword:"damage"});
	Cards.push({id:"H090",type:"S",color:"SX",name:"Sigil of Float",cost:"40",plus:"",st:"",hp:"",img:"sigiloffloat",rare:"R",keyword:"creature:spell:movement"});
	Cards.push({id:"H091",type:"S",color:"SG",name:"Prophecy",cost:"40",plus:"",st:"",hp:"",img:"prophecy",rare:"S",keyword:"draw"});
	Cards.push({id:"H092",type:"S",color:"SX",name:"Haste",cost:"70",plus:"",st:"",hp:"",img:"haste",rare:"S",keyword:"movement"});
	Cards.push({id:"H093",type:"S",color:"SY",name:"Penalize",cost:"80",plus:"",st:"",hp:"",img:"penalize",rare:"R",keyword:""});
	Cards.push({id:"H094",type:"S",color:"SG",name:"Poison Mind",cost:"20",plus:"",st:"",hp:"",img:"poisonmind",rare:"N",keyword:"draw"});
	Cards.push({id:"H095",type:"S",color:"SX",name:"Vortex",cost:"40",plus:"",st:"",hp:"",img:"vortex",rare:"S",keyword:"draw"});
	Cards.push({id:"H096",type:"S",color:"SG",name:"Wind of Hope",cost:"40",plus:"",st:"",hp:"",img:"windofhope",rare:"N",keyword:"draw"});
	Cards.push({id:"H097",type:"S",color:"SL",name:"Home Ground",cost:"100",plus:"",st:"",hp:"",img:"homeground",rare:"R",keyword:"secret:terrain:change"});
	Cards.push({id:"H098",type:"S",color:"SG",name:"Holy Banishment",cost:"90",plus:"",st:"",hp:"",img:"holybanishment",rare:"N",keyword:""});
	Cards.push({id:"H099",type:"S",color:"SX",name:"Holy Word 1",cost:"30",plus:"",st:"",hp:"",img:"holyword1",rare:"N",keyword:"movement"});
	Cards.push({id:"H100",type:"S",color:"SX",name:"Holy Word 3",cost:"10",plus:"",st:"",hp:"",img:"holyword3",rare:"N",keyword:"movement"});
	Cards.push({id:"H101",type:"S",color:"SX",name:"Holy Word 6",cost:"50",plus:"",st:"",hp:"",img:"holyword6",rare:"N",keyword:"movement"});
	Cards.push({id:"H102",type:"S",color:"SX",name:"Holy Word 8",cost:"80",plus:"",st:"",hp:"",img:"holyword8",rare:"S",keyword:"movement"});
	Cards.push({id:"H103",type:"S",color:"SZ",name:"Merciful World",cost:"50",plus:"",st:"",hp:"",img:"mercifulworld",rare:"R",keyword:""});
	Cards.push({id:"H104",type:"S",color:"SG",name:"Magma Shift",cost:"120",plus:"",st:"",hp:"",img:"magmashift",rare:"S",keyword:"terrain:change"});
	Cards.push({id:"H105",type:"S",color:"SG",name:"Magical Leap",cost:"70",plus:"",st:"",hp:"",img:"magicalleap",rare:"R",keyword:"movement"});
	Cards.push({id:"H106",type:"S",color:"SX",name:"Magic Shelter",cost:"70",plus:"",st:"",hp:"",img:"magicshelter",rare:"S",keyword:"untargetable"});
	Cards.push({id:"H107",type:"S",color:"SG",name:"Magic Bolt",cost:"50",plus:"",st:"",hp:"",img:"magicbolt",rare:"N",keyword:"damage"});
	Cards.push({id:"H108",type:"S",color:"SL",name:"Mass Growth",cost:"30",plus:"D",st:"",hp:"",img:"massgrowth",rare:"S",keyword:"synthesis"});
	Cards.push({id:"H109",type:"S",color:"SY",name:"Mass Phantasm",cost:"70",plus:"",st:"",hp:"",img:"massphantasm",rare:"N",keyword:""});
	Cards.push({id:"H110",type:"S",color:"SG",name:"Manna",cost:"0",plus:"",st:"",hp:"",img:"manna",rare:"N",keyword:"gain:magic"});
	Cards.push({id:"H111",type:"S",color:"SZ",name:"Misty World",cost:"50",plus:"",st:"",hp:"",img:"mistyworld",rare:"R",keyword:"untargetable"});
	Cards.push({id:"H112",type:"S",color:"SZ",name:"Mirror World",cost:"70",plus:"",st:"",hp:"",img:"mirrorworld",rare:"R",keyword:""});
	Cards.push({id:"H113",type:"S",color:"SG",name:"Miracle Call",cost:"70",plus:"",st:"",hp:"",img:"miraclecall",rare:"S",keyword:"draw"});
	Cards.push({id:"H114",type:"S",color:"SG",name:"Metamorphosis",cost:"80",plus:"D",st:"",hp:"",img:"metamorphosis",rare:"S",keyword:"card:destruction"});
	Cards.push({id:"H115",type:"S",color:"SX",name:"Metal Form",cost:"70",plus:"",st:"",hp:"",img:"metalform",rare:"R",keyword:"neutralizes"});
	Cards.push({id:"H116",type:"S",color:"SX",name:"Uniformity",cost:"60",plus:"",st:"",hp:"",img:"uniformity",rare:"S",keyword:""});
	Cards.push({id:"H117",type:"S",color:"SL",name:"Life Stream",cost:"50",plus:"",st:"",hp:"",img:"lifestream",rare:"N",keyword:""});
	Cards.push({id:"H118",type:"S",color:"SX",name:"Life Force",cost:"50",plus:"",st:"",hp:"",img:"lifeforce",rare:"S",keyword:""});
	Cards.push({id:"H119",type:"S",color:"SG",name:"Land Transfer",cost:"100",plus:"",st:"",hp:"",img:"landtransfer",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H120",type:"S",color:"SG",name:"Land Drain",cost:"50",plus:"",st:"",hp:"",img:"landdrain",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H121",type:"S",color:"SX",name:"Liquid Form",cost:"30",plus:"",st:"",hp:"",img:"liquidform",rare:"N",keyword:"draw"});
	Cards.push({id:"H122",type:"S",color:"SG",name:"Restore",cost:"40",plus:"",st:"",hp:"",img:"restore",rare:"N",keyword:""});
	Cards.push({id:"H123",type:"S",color:"SG",name:"Revival",cost:"80",plus:"",st:"",hp:"",img:"revival",rare:"R",keyword:""});
	Cards.push({id:"H124",type:"S",color:"SG",name:"Remission",cost:"100",plus:"D",st:"",hp:"",img:"remission",rare:"S",keyword:""});
	Cards.push({id:"H125",type:"S",color:"SG",name:"Remote Switch",cost:"30",plus:"",st:"",hp:"",img:"remoteswitch",rare:"S",keyword:"draw"});
	Cards.push({id:"H126",type:"S",color:"SX",name:"Release",cost:"50",plus:"",st:"",hp:"",img:"release",rare:"N",keyword:""});
	Cards.push({id:"H127",type:"S",color:"SG",name:"Relief",cost:"30",plus:"",st:"",hp:"",img:"relief",rare:"N",keyword:""});
	Cards.push({id:"H128",type:"S",color:"SG",name:"Reincarnation",cost:"70",plus:"",st:"",hp:"",img:"reincarnation",rare:"R",keyword:"draw"});
	Cards.push({id:"H129",type:"S",color:"SL",name:"Ray of Purge",cost:"50",plus:"",st:"",hp:"",img:"rayofpurge",rare:"R",keyword:"card:destruction"});
	Cards.push({id:"H130",type:"S",color:"SL",name:"Ray of Law",cost:"60",plus:"",st:"",hp:"",img:"rayoflaw",rare:"S",keyword:"card:destruction"});
	Cards.push({id:"H131",type:"S",color:"SL",name:"Redivision",cost:"100",plus:"",st:"",hp:"",img:"redivision",rare:"S",keyword:"gain:magic"});
	Cards.push({id:"H132",type:"S",color:"SG",name:"Long Line",cost:"70",plus:"",st:"",hp:"",img:"longline",rare:"S",keyword:"secret:gain:magic:draw"});
	Cards.push({id:"H133",type:"S",color:"SG",name:"Sense of Wild",cost:"80",plus:"",st:"",hp:"",img:"senseofwild",rare:"R",keyword:"draw"});
	//make the card name
	Cards.forEach(function(val, idx, arr){
		CName[val.id] = val.name;
	});
}